  //                           Field Update Operators
  //                            ----------*----------


  //  They are special MongoDB operators used to modify existing data inside a document without replacing the whole document.
  //     * Only specific field change.

  //     * Without operator:- whole document will change.


  //  1) $set:- Update an existing field or add new field if it is not present.
  //       Eg:- db.students.updateOne(
  //            {name:'Aishwarya'},
  //            {$set:{marks: 85, isPassed: true}}
  //            )

  //                    * If isPassed present ,will update the marks.
  //                    * Otherwise create a new field named isPassed.


  //  2) $unset :- delete a specific field
  //       Eg:- db.students.updateOne(
  //            {name:'Athira'},
  //            {$unset: {remarks: ''}}
  //            )   

  //                       * Delete field remarks of Athira 


  //  3) $inc  :- Increase or decrease numeric value
  //       Eg:-
  //      a)   db.students.updateOne(
  //            {name:'Asha'},{$inc:{marks:5}}
  //           )

  //                * If Asha's existing mark is 75, this will increase by 5 marks and updated to 80.

  //     b)     db.students.updateOne(
  //             {name: 'Asha'},{$inc:{marks:-5}}
  //            )

  //               * If Asha's existing mark is 75, & this will decrease by 5 marks and updated to 70.
  
  
  //    4) $rename : Chnge field name without change value.

  //        Eg:- db.students.updateOne(
  //              {name: 'Arpitha'},
  //              {$rename: {'dob': 'Date of Birth' }}
  //            )

  //    5) $mul :- Multiply a number of field
  //        Eg:- db.students.updateOne(
  //             {name:'Divya},
  //             {$mul:{marks:2}}
  //              )

  //               * If Divya's existing mark is 45, & this will multiply by 2 marks and updated to 90.


  //   6) $min  :- Updated if existing value is smaller than given value

  //         Eg:- db.students.updateOne(
  //             {name:'Divya},
  //             {$min:{marks:70}}
  //              )

 //                * If Divya's existing mark is 60, & this will  updated to 70.


   //   7) $max :- Updated if existing value is greater than given value

  //         Eg:- db.students.updateOne(
  //             {name:'Divya},
  //             {$max:{marks:70}}
  //              )

 //                * If Divya's existing mark is 90, & this will  updated to 70.



   //   8) $currentDate  :- Adds current date or time automatically

  //         Eg:- db.students.updateOne(
  //             {name:'Divya},
  //             {$cuurentDate:{createdAt:  true}}
  //              )

  //  Difference between currentDate and $set: { updatedAt: new Date() }:-
  //   ----------------------------------------------------------------

  //        currentDate                                      $set: { updatedAt: new Date() }
  //        -----------                                      -------------------------------
  // * Time is generated by MongoDB server                * new Date is created by Node.js/client
  // * Accurate and consistent                            * Can vary if system clock is wrong
  








       
